name = "CSTParser"
uuid = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
authors = ["Zac Nugent <zac.nugent@gmail.com>"]
version = "3.4.3"

[deps]
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"

[compat]
Tokenize = "0.5.29"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
